global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
- job_name: postgres
  static_configs:
  - targets: ['postgres-exporter:9187']

- job_name: 'sql_exporter'
  scrape_interval: 5m
  scrape_timeout: 10s
  static_configs:
  - targets: ['sql-exporter:9399']

- job_name: solr
  static_configs:
  - targets: ['solr-exporter:9854']
