global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
- job_name: postgres
  static_configs:
  - targets: ['postgres-exporter:9187']
- job_name: 'sql_exporter'
  static_configs:
  - targets: ['sql-exporter:9399']
