{
 "title": "Table Row Counts",
 "description": "Number of rows in each SIR-indexed table",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Area Count",
   "type": "gauge",
   "description": "Number of rows in the area table.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "alias": "fetched", "expr": "area_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Artist Count",
   "type": "gauge",
   "description": "Number of rows in the artist table.",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "alias": "fetched", "expr": "artist_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CD Stub Count",
   "type": "gauge",
   "description": "Number of rows in the release_raw table.",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cd_stub_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Editor Count",
   "type": "gauge",
   "description": "Number of rows in the editor table.",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "editor_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Event Count",
   "type": "gauge",
   "description": "Number of rows in the event table.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "event_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Genre Count",
   "type": "gauge",
   "description": "Number of rows in the genre table.",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "genre_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Instrument Count",
   "type": "gauge",
   "description": "Number of rows in the instrument table.",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "instrument_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Label Count",
   "type": "gauge",
   "description": "Number of rows in the label table.",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "label_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Place Count",
   "type": "gauge",
   "description": "Number of rows in the place table.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "place_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Recording Count",
   "type": "gauge",
   "description": "Number of rows in the recording table.",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "recording_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Release Count",
   "type": "gauge",
   "description": "Number of rows in the release table.",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "release_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Release Group Count",
   "type": "gauge",
   "description": "Number of rows in the release_group table.",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "release_group_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Series Count",
   "type": "gauge",
   "description": "Number of rows in the series table.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "series_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tag Count",
   "type": "gauge",
   "description": "Number of rows in the tag table.",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tag_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "URL Count",
   "type": "gauge",
   "description": "Number of rows in the url table.",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "url_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Work Count",
   "type": "gauge",
   "description": "Number of rows in the work table.",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "work_count", "legendFormat": "__auto" }
   ]
  }
 ]
}