version: '3.1'

# Description: Build and run monitoring features (Prometheus/Grafana)

services:
  db:
    command: postgres -c "shared_buffers=2048MB" -c "shared_preload_libraries=pg_amqp.so, pg_stat_statements" -c pg_stat_statements.track=all

  search:
    expose:
      - 9983

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    expose:
      - 9090
    command: --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./default/prometheus.yaml:/etc/prometheus/prometheus.yaml
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "${MUSICBRAINZ_DOCKER_HOST_IPADDRCOL:-}3050:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./default/grafana-provisioning:/etc/grafana/provisioning
    depends_on:
      - solr-exporter
      - postgres-exporter
      - prometheus
      - sql-exporter

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    expose:
      - 9187
    command: --config.file=/etc/postgres-exporter/postgres-exporter.yml
    volumes:
      - ./default/postgres-exporter.yml:/etc/postgres-exporter/postgres-exporter.yml
    environment:
      DATA_SOURCE_NAME: "postgres://musicbrainz:musicbrainz@db:5432/musicbrainz_db?sslmode=disable"
    depends_on:
      prometheus:
        condition: service_started
      db:
        condition: service_started
    restart: unless-stopped
  sql-exporter:
    image: burningalchemist/sql_exporter
    container_name: sql-exporter
    expose:
      - 9399
    command: --config.file=/etc/sql-exporter/sql-exporter.yml
    volumes:
      - ./default/sql-exporter.yml:/etc/sql-exporter/sql-exporter.yml
    depends_on:
      prometheus:
        condition: service_started
      db:
        condition: service_started
    restart: unless-stopped
    

  solr-exporter:
    build:
      context: build/solr
      args:
        - MB_SOLR_VERSION=${MB_SOLR_VERSION:-solr-9.7.0}
    image: musicbrainz-docker_search:${MB_SOLR_VERSION:-solr-9.7.0}
    container_name: solr-exporter
    expose:
      - 9854
    command: sh -c 'cd /opt/solr-9.7.0/contrib/prometheus-exporter; exec bin/solr-exporter -p 9854 -z search:9983 -f conf/solr-exporter-config.xml'
    depends_on:
      prometheus:
        condition: service_started
      search:
        condition: service_healthy
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    expose:
      - 9100
    volumes:
      - "/:/host:ro,rslave"
      - node-exporter-textfile-collector:/textfile-collector-directory
    command:
      - --path.rootfs=/host
      #- --collector.filesystem.fs-types-exclude="^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|nsfs|tmpfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$"
      #- --collector.filesystem.mount-points-exclude="^/(dev|proc|sys|var/lib/docker/.+)($|/)"
      - --no-collector.filesystem
      - --collector.mountstats
      - --collector.textfile.directory=/textfile-collector-directory

  rabbitmq-exporter:
    image: kbudde/rabbitmq-exporter
    container_name: rabbitmq-exporter
    restart: unless-stopped
    expose:
      - 9419
    environment:
      RABBIT_URL: http://mq:15672
      RABBIT_USER: sir
      RABBIT_PASSWORD: sir

volumes:
  grafana-storage: {}
  node-exporter-textfile-collector: {}
