version: '3.1'

# Description: Build and run monitoring features (Prometheus/Grafana)

services:
  db:
    command: postgres -c "shared_buffers=2048MB" -c "shared_preload_libraries=pg_amqp.so, pg_stat_statements" -c pg_stat_statements.track=all

  prometheus:
    image: prom/prometheus
    expose:
      - 9090
    command: --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./default/prometheus.yaml:/etc/prometheus/prometheus.yaml

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - "${MUSICBRAINZ_DOCKER_HOST_IPADDRCOL:-}3050:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./default/grafana-provisioning:/etc/grafana/provisioning
    depends_on:
      - postgres-exporter
      - prometheus

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    expose:
      - 9187
    command: --config.file=/etc/postgres-exporter/postgres-exporter.yml
    volumes:
      - ./default/postgres-exporter.yml:/etc/postgres-exporter/postgres-exporter.yml
    environment:
      DATA_SOURCE_NAME: "postgres://musicbrainz:musicbrainz@db:5432/musicbrainz_db?sslmode=disable"
    depends_on:
      prometheus:
        condition: service_started
      db:
        condition: service_started
    restart: unless-stopped

volumes:
  grafana-storage: {}
