# Description: Build multi arch version of the docker image

services:
  musicbrainz:
    image: ${DEST_IMAGE_TAG}
    build:
      context: build/musicbrainz
      platforms:
        - linux/arm64
        - linux/amd64
