#!/bin/bash

set -e -u

source "$(dirname "${BASH_SOURCE[0]}")/lib/common.inc.bash"

HELP=$(cat <<EOH
Usage: $SCRIPT_NAME

Create 'amqp' extension (with broker) in the database.
EOH
)

Commands:
if [ $# -ne 0 ]
then
  echo >&2 "$SCRIPT_NAME: too many arguments"
  echo >&2 "$HELP"
  exit 64
fi

LOCAL_SQL_FILE="$(dirname "${BASH_SOURCE[0]}")/.create-amqp-extension.sql"
REMOTE_SQL_FILE=/tmp/CreateExtensionAMQP.sql

if ! $DOCKER_COMPOSE_CMD ps indexer | grep -qw 'Up'
then
  echo >&2 "$SCRIPT_NAME: cannot install: 'indexer' is not a running Docker Compose service"
  exit 69
fi

if [ -e "$LOCAL_SQL_FILE" ]
then
  echo >&2 "$SCRIPT_NAME: cannot install: file '$LOCAL_SQL_FILE' exists"
  exit 70
fi

if $DOCKER_COMPOSE_CMD exec db test -e "$REMOTE_SQL_FILE"
then
  echo >&2 "$SCRIPT_NAME: cannot install: file '$REMOTE_SQL_FILE' exists in 'db' Docker Compose service"
  exit 70
fi

echo "Installing indexer AMQP extension into PostgreSQL ..."

$DOCKER_COMPOSE_CMD exec indexer python -m sir extension

indexer_container_id="$($DOCKER_COMPOSE_CMD ps -q indexer)"
$DOCKER_CMD cp "$indexer_container_id:/code/sql/CreateExtension.sql" "$LOCAL_SQL_FILE"
$DOCKER_CMD cp "$LOCAL_SQL_FILE" "$indexer_container_id:$REMOTE_SQL_FILE"

$DOCKER_COMPOSE_CMD exec db psql -U musicbrainz -d musicbrainz_db -f "$REMOTE_SQL_FILE"

$DOCKER_COMPOSE_CMD exec db rm -f "$REMOTE_SQL_FILE"
rm -f "$LOCAL_SQL_FILE"

echo "Successfully created amqp extension in the database."

# vi: set et sts=2 sw=2 ts=2 :
