#!/usr/bin/env bash

set -e -u

# shellcheck source=admin/lib/common.inc.bash
source "$(dirname "${BASH_SOURCE[0]}")/lib/common.inc.bash"

HELP=$(cat <<EOH
Usage: $SCRIPT_NAME [--help]

Purge message queues for search index rebuilder.
EOH
)

if [[ $# -ne 0 && $1 =~ -*h(elp)? ]]
then
  echo "$HELP"
  exit 0 # EX_OK
elif [[ $# -ne 0 ]]
then
  echo >&2 "$SCRIPT_NAME: unrecognized argument: $1"
  echo >&2 "Try '$SCRIPT_NAME help' for usage."
  exit 64 # EX_USAGE
fi

# Check whether the `db` service is up.

was_db_up='no'
if is_service_running db
then
  was_db_up='yes'
else
  $DOCKER_COMPOSE_CMD up -d db
  $DOCKER_COMPOSE_CMD exec db pg_isready -U musicbrainz
fi

echo 'DELETE FROM sir.pending_data;' | \
  sudo docker compose exec -T db psql -U musicbrainz -d musicbrainz_db

# Stop PostgreSQL if it was not initially up

if [[ $was_db_up == 'no' ]]
then
  $DOCKER_COMPOSE_CMD stop db
fi

# vi: set et sts=2 sw=2 ts=2 :
