#!/bin/bash

set -e -u

source "$(dirname "${BASH_SOURCE[0]}")/lib/common.inc.bash"

HELP=$(cat <<EOH
Usage: $SCRIPT_NAME <clean|install|uninstall>

Commands:
  clean       Remove temporary install scripts and uninstall scripts.
  install     Create database triggers and add uninstall scripts.
  uninstall   Drop database triggers and remove uninstall scripts.
EOH
)

if [ $# -ne 1 ]
then
  echo >&2 "$SCRIPT_NAME: wrong number of arguments"
  echo >&2 "$HELP"
  exit 64
fi

LOCAL_TRIGGERS_DIR="$(dirname "${BASH_SOURCE[0]}")/.setup-amqp-triggers-sql"
REMOTE_TRIGGERS_DIR=/tmp/indexer-sql

case "$1" in
  clean     )
    if ! $DOCKER_COMPOSE_CMD ps musicbrainz | grep -qw 'Up'
    then
      echo >&2 "$SCRIPT_NAME: cannot clean: 'musicbrainz' is not a running docker compose service"
      exit 69
    fi

    echo "Cleaning indexer triggers install/uninstall scripts up ..."

    $DOCKER_COMPOSE_CMD exec musicbrainz rm -frv "$REMOTE_TRIGGERS_DIR"
    rm -frv "$LOCAL_TRIGGERS_DIR"
    ;;
  install   )
    if ! $DOCKER_COMPOSE_CMD ps indexer | grep -qw 'Up'
    then
      echo >&2 "$SCRIPT_NAME: cannot install: 'indexer' is not a running docker compose service"
      exit 69
    fi

    if [ -e "$LOCAL_TRIGGERS_DIR" ]
    then
      echo >&2 "$SCRIPT_NAME: cannot install: file '$LOCAL_TRIGGERS_DIR' exists"
      exit 70
    fi

    if $DOCKER_COMPOSE_CMD exec musicbrainz test -e "$REMOTE_TRIGGERS_DIR"
    then
      echo >&2 "$SCRIPT_NAME: cannot install: file '$REMOTE_TRIGGERS_DIR' exists in 'musicbrainz' docker compose service"
      exit 70
    fi

    echo "Installing indexer triggers ..."

    $DOCKER_COMPOSE_CMD exec indexer python -m sir triggers

    indexer_container_id="$($DOCKER_COMPOSE_CMD ps -q indexer)"
    $DOCKER_CMD cp "$indexer_container_id":/code/sql "$LOCAL_TRIGGERS_DIR"
    $DOCKER_CMD cp "$LOCAL_TRIGGERS_DIR" "$indexer_container_id":"$REMOTE_TRIGGERS_DIR"

    $DOCKER_COMPOSE_CMD exec musicbrainz /indexer-triggers.sh "$REMOTE_TRIGGERS_DIR" create

    rm -fr "$LOCAL_TRIGGERS_DIR"
    ;;
  uninstall )
    if ! $DOCKER_COMPOSE_CMD ps musicbrainz | grep -qw 'Up'
    then
      echo >&2 "$SCRIPT_NAME: cannot uninstall: 'musicbrainz' is not a running docker compose service"
      exit 69
    fi

    if $DOCKER_COMPOSE_CMD exec musicbrainz test ! -e "$REMOTE_TRIGGERS_DIR"
    then
      echo >&2 "$SCRIPT_NAME: cannot uninstall: file '$REMOTE_TRIGGERS_DIR' does not exist"
      exit 70
    fi

    echo "Uninstalling indexer triggers ..."

    $DOCKER_COMPOSE_CMD exec musicbrainz /indexer-triggers.sh "$REMOTE_TRIGGERS_DIR" drop

    $DOCKER_COMPOSE_CMD exec musicbrainz rm -fr "$REMOTE_TRIGGERS_DIR"
    ;;
  *         )
    echo >&2 "$SCRIPT_NAME: unrecognized command '$1'"
    echo >&2 "$HELP"
    exit 64
    ;;
esac

echo "Done."

# vi: set et sts=2 sw=2 ts=2 :
